[tool.poetry]
name = "job-hunting-helper"
version = "0.1.0"
description = "An app to help on the job-hunting process"
authors = ["Ulises Alexander Arguelles Monjaraz <ulises_alexander_am@protonmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "job_hunting_helper"}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
